// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/customer": {
            "get": {
                "description": "Menampilkan data dalam jumlah yang banyak, biasanya untuk tabel",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Customer"
                ],
                "summary": "Menampilkan data semua customer",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.ApiResponse-array_responses_CustomerResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.ApiResponse-any"
                        }
                    }
                }
            },
            "post": {
                "description": "Menambahkan data customer kedalam database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Customer"
                ],
                "summary": "Membuat data customer",
                "parameters": [
                    {
                        "description": "Create Data Customer",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/requests.CreateCustomerRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/responses.ApiResponse-responses_CustomerResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.ApiResponse-requests_CreateCustomerRequest"
                        }
                    }
                }
            },
            "delete": {
                "description": "Menghapus data customer tetapi dapat dipulihkan nantinya",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Customer"
                ],
                "summary": "Menghapus (soft delete) data customer",
                "parameters": [
                    {
                        "description": "Delete Data Customer",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/requests.DeleteCustomerRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/responses.ApiResponse-responses_CustomerResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.ApiResponse-requests_DeleteCustomerRequest"
                        }
                    }
                }
            },
            "patch": {
                "description": "Mengubah Data Customer",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Customer"
                ],
                "summary": "Mengubah Data Customer",
                "parameters": [
                    {
                        "description": "Update Data Customer",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/requests.UpdateCustomerRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/responses.ApiResponse-responses_CustomerResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.ApiResponse-requests_UpdateCustomerRequest"
                        }
                    }
                }
            }
        },
        "/customer/all": {
            "get": {
                "description": "Menampilkan semua data-data customer bahkan yang telah terhapus",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Customer"
                ],
                "summary": "Menampilkan semua data-data customer bahkan yang telah terhapus",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.ApiResponse-array_responses_CustomerResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.ApiResponse-any"
                        }
                    }
                }
            }
        },
        "/customer/deleted": {
            "get": {
                "description": "Menampilkan data-data customer yang terhapus (Soft delete)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Customer"
                ],
                "summary": "Menampilkan data semua customer yang terhapus",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.ApiResponse-array_responses_CustomerResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.ApiResponse-any"
                        }
                    }
                }
            }
        },
        "/customer/force": {
            "delete": {
                "description": "Menghapus secara permanen data customer (hard delete)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Customer"
                ],
                "summary": "Menghapus secara permanen data customer",
                "parameters": [
                    {
                        "description": "Hard Delete Data Customer",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/requests.DeleteCustomerRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/responses.ApiResponse-responses_CustomerResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.ApiResponse-requests_DeleteCustomerRequest"
                        }
                    }
                }
            }
        },
        "/customer/restore": {
            "post": {
                "description": "Memulihakan data customer yang terhapus (soft delete)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Customer"
                ],
                "summary": "Memulihkan Data Customer",
                "parameters": [
                    {
                        "description": "Restore Data Customer",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/requests.RestoreCustomerRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/responses.ApiResponse-responses_CustomerResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.ApiResponse-requests_RestoreCustomerRequest"
                        }
                    }
                }
            }
        },
        "/sales": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sales"
                ],
                "summary": "Menampilkan data sales",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.ApiResponse-array_responses_SalesResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.ApiResponse-any"
                        }
                    }
                }
            },
            "post": {
                "description": "Menambahkan data sales kedalam tabel sales atau halaman kelola sales",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sales"
                ],
                "summary": "Membuat data sales",
                "parameters": [
                    {
                        "description": "Create Data Sales",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/requests.CreateSalesRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/responses.ApiResponse-responses_SalesResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.ApiResponse-requests_CreateSalesRequest"
                        }
                    }
                }
            },
            "delete": {
                "description": "Menghapus data sales tetapi dapat dipulihkan nantinya",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sales"
                ],
                "summary": "Menghapus (soft delete) data sales",
                "parameters": [
                    {
                        "description": "Delete Data Sales",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/requests.DeleteSalesRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/responses.ApiResponse-responses_SalesResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.ApiResponse-requests_DeleteSalesRequest"
                        }
                    }
                }
            },
            "patch": {
                "description": "Mengubah data sales sebagaian atau semua data sales",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sales"
                ],
                "summary": "Mengubah data sales secara patch",
                "parameters": [
                    {
                        "description": "Update Data Sales",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/requests.UpdateSalesRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/responses.ApiResponse-responses_SalesResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.ApiResponse-requests_UpdateSalesRequest"
                        }
                    }
                }
            }
        },
        "/sales/all": {
            "get": {
                "description": "Menampilkan semua data-data sales bahkan yang telah terhapus",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sales"
                ],
                "summary": "Menampilkan semua data-data sales bahkan yang telah terhapus",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.ApiResponse-array_responses_SalesResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.ApiResponse-any"
                        }
                    }
                }
            }
        },
        "/sales/deleted": {
            "get": {
                "description": "Menampilkan data-data sales yang terhapus (Soft delete)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sales"
                ],
                "summary": "Menampilkan data-data sales yang terhapus",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.ApiResponse-array_responses_SalesResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.ApiResponse-any"
                        }
                    }
                }
            }
        },
        "/sales/force": {
            "delete": {
                "description": "Menghapus secara permanen data sales (hard delete)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sales"
                ],
                "summary": "Menghapus secara permanen data sales",
                "parameters": [
                    {
                        "description": "Hard Delete Data Sales",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/requests.DeleteSalesRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/responses.ApiResponse-responses_SalesResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.ApiResponse-requests_DeleteSalesRequest"
                        }
                    }
                }
            }
        },
        "/sales/restore": {
            "post": {
                "description": "Memulihkan data sales yang terhapus (soft delete)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sales"
                ],
                "summary": "Memulihkan data sales",
                "parameters": [
                    {
                        "description": "Restore Data Sales",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/requests.RestoreSalesRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/responses.ApiResponse-responses_SalesResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.ApiResponse-requests_RestoreSalesRequest"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "requests.CreateCustomerRequest": {
            "type": "object",
            "required": [
                "kode_owner",
                "kontak_outlet",
                "kontak_owner",
                "nama_brand",
                "nama_outlet",
                "nama_owner"
            ],
            "properties": {
                "kode_owner": {
                    "type": "string"
                },
                "kontak_outlet": {
                    "type": "string"
                },
                "kontak_owner": {
                    "type": "string"
                },
                "nama_brand": {
                    "type": "string"
                },
                "nama_outlet": {
                    "type": "string"
                },
                "nama_owner": {
                    "type": "string"
                },
                "sales_id": {
                    "type": "integer"
                }
            }
        },
        "requests.CreateSalesRequest": {
            "type": "object",
            "required": [
                "email_sales",
                "kontak_sales",
                "nama_sales",
                "password_sales"
            ],
            "properties": {
                "email_sales": {
                    "type": "string"
                },
                "is_super_admin": {
                    "type": "boolean"
                },
                "kontak_sales": {
                    "type": "string"
                },
                "nama_sales": {
                    "type": "string"
                },
                "password_sales": {
                    "type": "string"
                }
            }
        },
        "requests.DeleteCustomerRequest": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                }
            }
        },
        "requests.DeleteSalesRequest": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                }
            }
        },
        "requests.RestoreCustomerRequest": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                }
            }
        },
        "requests.RestoreSalesRequest": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                }
            }
        },
        "requests.UpdateCustomerRequest": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "kode_owner": {
                    "type": "string"
                },
                "kontak_outlet": {
                    "type": "string"
                },
                "kontak_owner": {
                    "type": "string"
                },
                "nama_brand": {
                    "type": "string"
                },
                "nama_outlet": {
                    "type": "string"
                },
                "nama_owner": {
                    "type": "string"
                },
                "sales_id": {
                    "type": "integer"
                }
            }
        },
        "requests.UpdateSalesRequest": {
            "type": "object",
            "properties": {
                "email_sales": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_super_admin": {
                    "type": "boolean"
                },
                "kontak_sales": {
                    "type": "string"
                },
                "nama_sales": {
                    "type": "string"
                },
                "password_sales": {
                    "type": "string"
                }
            }
        },
        "responses.ApiResponse-any": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string"
                }
            }
        },
        "responses.ApiResponse-array_responses_CustomerResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/responses.CustomerResponse"
                    }
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "responses.ApiResponse-array_responses_SalesResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/responses.SalesResponse"
                    }
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "responses.ApiResponse-requests_CreateCustomerRequest": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/requests.CreateCustomerRequest"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "responses.ApiResponse-requests_CreateSalesRequest": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/requests.CreateSalesRequest"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "responses.ApiResponse-requests_DeleteCustomerRequest": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/requests.DeleteCustomerRequest"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "responses.ApiResponse-requests_DeleteSalesRequest": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/requests.DeleteSalesRequest"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "responses.ApiResponse-requests_RestoreCustomerRequest": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/requests.RestoreCustomerRequest"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "responses.ApiResponse-requests_RestoreSalesRequest": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/requests.RestoreSalesRequest"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "responses.ApiResponse-requests_UpdateCustomerRequest": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/requests.UpdateCustomerRequest"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "responses.ApiResponse-requests_UpdateSalesRequest": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/requests.UpdateSalesRequest"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "responses.ApiResponse-responses_CustomerResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/responses.CustomerResponse"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "responses.ApiResponse-responses_SalesResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/responses.SalesResponse"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "responses.CustomerResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "kode_owner": {
                    "type": "string"
                },
                "kontak_outler": {
                    "type": "string"
                },
                "kontak_owner": {
                    "type": "string"
                },
                "nama_brand": {
                    "type": "string"
                },
                "nama_outlet": {
                    "type": "string"
                },
                "nama_owner": {
                    "type": "string"
                },
                "sales": {
                    "$ref": "#/definitions/responses.SalesSummaryResponse"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "responses.SalesResponse": {
            "type": "object",
            "properties": {
                "email_sales": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_super_admin": {
                    "type": "boolean"
                },
                "kontak_sales": {
                    "type": "string"
                },
                "nama_sales": {
                    "type": "string"
                }
            }
        },
        "responses.SalesSummaryResponse": {
            "type": "object",
            "properties": {
                "sales_id": {
                    "type": "integer"
                },
                "sales_name": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Backend CRM Piposmart",
	Description:      "Backend API untuk aplikasi frontend CRM Piposmart",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
