basePath: /
definitions:
  requests.CreateCustomerRequest:
    properties:
      kode_owner:
        type: string
      kontak_outlet:
        type: string
      kontak_owner:
        type: string
      nama_brand:
        type: string
      nama_outlet:
        type: string
      nama_owner:
        type: string
      sales_id:
        type: integer
    required:
    - kode_owner
    - kontak_outlet
    - kontak_owner
    - nama_brand
    - nama_outlet
    - nama_owner
    type: object
  requests.CreateSalesRequest:
    properties:
      email_sales:
        type: string
      is_super_admin:
        type: boolean
      kontak_sales:
        type: string
      nama_sales:
        type: string
      password_sales:
        type: string
    required:
    - email_sales
    - kontak_sales
    - nama_sales
    - password_sales
    type: object
  requests.DeleteCustomerRequest:
    properties:
      id:
        type: integer
    type: object
  requests.DeleteSalesRequest:
    properties:
      id:
        type: integer
    type: object
  requests.RestoreCustomerRequest:
    properties:
      id:
        type: integer
    type: object
  requests.RestoreSalesRequest:
    properties:
      id:
        type: integer
    type: object
  requests.UpdateCustomerRequest:
    properties:
      id:
        type: integer
      kode_owner:
        type: string
      kontak_outlet:
        type: string
      kontak_owner:
        type: string
      nama_brand:
        type: string
      nama_outlet:
        type: string
      nama_owner:
        type: string
      sales_id:
        type: integer
    type: object
  requests.UpdateSalesRequest:
    properties:
      email_sales:
        type: string
      id:
        type: integer
      is_super_admin:
        type: boolean
      kontak_sales:
        type: string
      nama_sales:
        type: string
      password_sales:
        type: string
    type: object
  responses.ApiResponse-any:
    properties:
      data: {}
      message:
        type: string
    type: object
  responses.ApiResponse-array_responses_CustomerResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/responses.CustomerResponse'
        type: array
      message:
        type: string
    type: object
  responses.ApiResponse-array_responses_SalesResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/responses.SalesResponse'
        type: array
      message:
        type: string
    type: object
  responses.ApiResponse-requests_CreateCustomerRequest:
    properties:
      data:
        $ref: '#/definitions/requests.CreateCustomerRequest'
      message:
        type: string
    type: object
  responses.ApiResponse-requests_CreateSalesRequest:
    properties:
      data:
        $ref: '#/definitions/requests.CreateSalesRequest'
      message:
        type: string
    type: object
  responses.ApiResponse-requests_DeleteCustomerRequest:
    properties:
      data:
        $ref: '#/definitions/requests.DeleteCustomerRequest'
      message:
        type: string
    type: object
  responses.ApiResponse-requests_DeleteSalesRequest:
    properties:
      data:
        $ref: '#/definitions/requests.DeleteSalesRequest'
      message:
        type: string
    type: object
  responses.ApiResponse-requests_RestoreCustomerRequest:
    properties:
      data:
        $ref: '#/definitions/requests.RestoreCustomerRequest'
      message:
        type: string
    type: object
  responses.ApiResponse-requests_RestoreSalesRequest:
    properties:
      data:
        $ref: '#/definitions/requests.RestoreSalesRequest'
      message:
        type: string
    type: object
  responses.ApiResponse-requests_UpdateCustomerRequest:
    properties:
      data:
        $ref: '#/definitions/requests.UpdateCustomerRequest'
      message:
        type: string
    type: object
  responses.ApiResponse-requests_UpdateSalesRequest:
    properties:
      data:
        $ref: '#/definitions/requests.UpdateSalesRequest'
      message:
        type: string
    type: object
  responses.ApiResponse-responses_CustomerResponse:
    properties:
      data:
        $ref: '#/definitions/responses.CustomerResponse'
      message:
        type: string
    type: object
  responses.ApiResponse-responses_SalesResponse:
    properties:
      data:
        $ref: '#/definitions/responses.SalesResponse'
      message:
        type: string
    type: object
  responses.CustomerResponse:
    properties:
      created_at:
        type: string
      id:
        type: integer
      kode_owner:
        type: string
      kontak_outler:
        type: string
      kontak_owner:
        type: string
      nama_brand:
        type: string
      nama_outlet:
        type: string
      nama_owner:
        type: string
      sales:
        $ref: '#/definitions/responses.SalesSummaryResponse'
      updated_at:
        type: string
    type: object
  responses.SalesResponse:
    properties:
      email_sales:
        type: string
      id:
        type: integer
      is_super_admin:
        type: boolean
      kontak_sales:
        type: string
      nama_sales:
        type: string
    type: object
  responses.SalesSummaryResponse:
    properties:
      sales_id:
        type: integer
      sales_name:
        type: string
    type: object
info:
  contact: {}
  description: Backend API untuk aplikasi frontend CRM Piposmart
  title: Backend CRM Piposmart
  version: "0.1"
paths:
  /customer:
    delete:
      consumes:
      - application/json
      description: Menghapus data customer tetapi dapat dipulihkan nantinya
      parameters:
      - description: Delete Data Customer
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/requests.DeleteCustomerRequest'
      produces:
      - application/json
      responses:
        "202":
          description: Accepted
          schema:
            $ref: '#/definitions/responses.ApiResponse-responses_CustomerResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.ApiResponse-requests_DeleteCustomerRequest'
      summary: Menghapus (soft delete) data customer
      tags:
      - Customer
    get:
      consumes:
      - application/json
      description: Menampilkan data dalam jumlah yang banyak, biasanya untuk tabel
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.ApiResponse-array_responses_CustomerResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.ApiResponse-any'
      summary: Menampilkan data semua customer
      tags:
      - Customer
    patch:
      consumes:
      - application/json
      description: Mengubah Data Customer
      parameters:
      - description: Update Data Customer
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/requests.UpdateCustomerRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/responses.ApiResponse-responses_CustomerResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.ApiResponse-requests_UpdateCustomerRequest'
      summary: Mengubah Data Customer
      tags:
      - Customer
    post:
      consumes:
      - application/json
      description: Menambahkan data customer kedalam database
      parameters:
      - description: Create Data Customer
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/requests.CreateCustomerRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/responses.ApiResponse-responses_CustomerResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.ApiResponse-requests_CreateCustomerRequest'
      summary: Membuat data customer
      tags:
      - Customer
  /customer/all:
    get:
      consumes:
      - application/json
      description: Menampilkan semua data-data customer bahkan yang telah terhapus
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.ApiResponse-array_responses_CustomerResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.ApiResponse-any'
      summary: Menampilkan semua data-data customer bahkan yang telah terhapus
      tags:
      - Customer
  /customer/deleted:
    get:
      consumes:
      - application/json
      description: Menampilkan data-data customer yang terhapus (Soft delete)
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.ApiResponse-array_responses_CustomerResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.ApiResponse-any'
      summary: Menampilkan data semua customer yang terhapus
      tags:
      - Customer
  /customer/force:
    delete:
      consumes:
      - application/json
      description: Menghapus secara permanen data customer (hard delete)
      parameters:
      - description: Hard Delete Data Customer
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/requests.DeleteCustomerRequest'
      produces:
      - application/json
      responses:
        "202":
          description: Accepted
          schema:
            $ref: '#/definitions/responses.ApiResponse-responses_CustomerResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.ApiResponse-requests_DeleteCustomerRequest'
      summary: Menghapus secara permanen data customer
      tags:
      - Customer
  /customer/restore:
    post:
      consumes:
      - application/json
      description: Memulihakan data customer yang terhapus (soft delete)
      parameters:
      - description: Restore Data Customer
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/requests.RestoreCustomerRequest'
      produces:
      - application/json
      responses:
        "202":
          description: Accepted
          schema:
            $ref: '#/definitions/responses.ApiResponse-responses_CustomerResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.ApiResponse-requests_RestoreCustomerRequest'
      summary: Memulihkan Data Customer
      tags:
      - Customer
  /sales:
    delete:
      consumes:
      - application/json
      description: Menghapus data sales tetapi dapat dipulihkan nantinya
      parameters:
      - description: Delete Data Sales
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/requests.DeleteSalesRequest'
      produces:
      - application/json
      responses:
        "202":
          description: Accepted
          schema:
            $ref: '#/definitions/responses.ApiResponse-responses_SalesResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.ApiResponse-requests_DeleteSalesRequest'
      summary: Menghapus (soft delete) data sales
      tags:
      - Sales
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.ApiResponse-array_responses_SalesResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.ApiResponse-any'
      summary: Menampilkan data sales
      tags:
      - Sales
    patch:
      consumes:
      - application/json
      description: Mengubah data sales sebagaian atau semua data sales
      parameters:
      - description: Update Data Sales
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/requests.UpdateSalesRequest'
      produces:
      - application/json
      responses:
        "202":
          description: Accepted
          schema:
            $ref: '#/definitions/responses.ApiResponse-responses_SalesResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.ApiResponse-requests_UpdateSalesRequest'
      summary: Mengubah data sales secara patch
      tags:
      - Sales
    post:
      consumes:
      - application/json
      description: Menambahkan data sales kedalam tabel sales atau halaman kelola
        sales
      parameters:
      - description: Create Data Sales
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/requests.CreateSalesRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/responses.ApiResponse-responses_SalesResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.ApiResponse-requests_CreateSalesRequest'
      summary: Membuat data sales
      tags:
      - Sales
  /sales/all:
    get:
      consumes:
      - application/json
      description: Menampilkan semua data-data sales bahkan yang telah terhapus
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.ApiResponse-array_responses_SalesResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.ApiResponse-any'
      summary: Menampilkan semua data-data sales bahkan yang telah terhapus
      tags:
      - Sales
  /sales/deleted:
    get:
      consumes:
      - application/json
      description: Menampilkan data-data sales yang terhapus (Soft delete)
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.ApiResponse-array_responses_SalesResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.ApiResponse-any'
      summary: Menampilkan data-data sales yang terhapus
      tags:
      - Sales
  /sales/force:
    delete:
      consumes:
      - application/json
      description: Menghapus secara permanen data sales (hard delete)
      parameters:
      - description: Hard Delete Data Sales
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/requests.DeleteSalesRequest'
      produces:
      - application/json
      responses:
        "202":
          description: Accepted
          schema:
            $ref: '#/definitions/responses.ApiResponse-responses_SalesResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.ApiResponse-requests_DeleteSalesRequest'
      summary: Menghapus secara permanen data sales
      tags:
      - Sales
  /sales/restore:
    post:
      consumes:
      - application/json
      description: Memulihkan data sales yang terhapus (soft delete)
      parameters:
      - description: Restore Data Sales
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/requests.RestoreSalesRequest'
      produces:
      - application/json
      responses:
        "202":
          description: Accepted
          schema:
            $ref: '#/definitions/responses.ApiResponse-responses_SalesResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.ApiResponse-requests_RestoreSalesRequest'
      summary: Memulihkan data sales
      tags:
      - Sales
swagger: "2.0"
