package analytics

import "fmt"

var registry = []DiagramCatalogItem{
	newDiagram("owners", "growth-trend", "Tren Pertumbuhan Owner", "line", "Melihat pertumbuhan owner baru.", "Melihat owner baru per periode.", "Semakin tinggi garis, semakin banyak owner baru.", "Mengetahui akuisisi owner meningkat atau menurun.", "higher_is_better"),
	newDiagram("owners", "ownership-distribution", "Distribusi Kepemilikan Owner", "stacked_bar", "Melihat owner milik Admin, Supervisor, atau Sales.", "Mengetahui penumpukan ownership owner.", "Bandingkan besaran setiap role ownership.", "Menentukan apakah distribusi owner sudah sehat.", "balanced_is_better"),
	newDiagram("owners", "province-distribution", "Distribusi Owner per Provinsi", "bar", "Melihat persebaran owner per provinsi.", "Mengetahui provinsi dengan owner terbanyak.", "Bandingkan tinggi batang per provinsi.", "Menentukan prioritas wilayah akuisisi.", "higher_is_better"),
	newDiagram("owners", "city-top10", "Top 10 Kota Owner", "bar", "Melihat kota owner terbanyak.", "Mengetahui hotspot owner.", "Urutkan kota dengan jumlah owner tertinggi.", "Menentukan fokus kota paling potensial.", "higher_is_better"),
	newDiagram("owners", "soft-delete-trend", "Tren Soft Delete Owner", "line", "Melihat owner yang dihapus secara soft delete.", "Mengetahui kualitas input owner.", "Semakin tinggi garis, semakin banyak owner dihapus.", "Menilai apakah kualitas data memburuk atau membaik.", "lower_is_better"),
	newDiagram("outlets", "growth-trend", "Tren Pertumbuhan Outlet", "line", "Melihat pertumbuhan outlet baru.", "Mengetahui ekspansi outlet customer.", "Semakin tinggi garis, semakin banyak outlet baru.", "Mengukur perkembangan jaringan outlet.", "higher_is_better"),
	newDiagram("outlets", "outlet-per-owner-histogram", "Distribusi Outlet per Owner", "histogram", "Melihat owner single outlet vs multi-outlet.", "Mengetahui struktur basis customer.", "Lihat bucket owner dengan jumlah outlet tertentu.", "Membantu segmentasi owner kecil dan besar.", "higher_is_better"),
	newDiagram("outlets", "subscription-status-recap", "Rekap Status Langganan Outlet", "stacked_bar", "Melihat distribusi status langganan outlet.", "Mengetahui kesehatan basis outlet.", "Baca komposisi status per periode.", "Menentukan fokus retention, renewal, atau win-back.", "higher_is_better"),
	newDiagram("outlets", "not-subscribe-trend", "Tren Outlet Not Subscribe", "line", "Melihat outlet yang tidak lagi berlangganan.", "Mengetahui churn berat.", "Semakin tinggi garis, semakin banyak outlet keluar dari ekosistem langganan.", "Menentukan urgensi program reaktivasi.", "lower_is_better"),
	newDiagram("owners", "indonesia-distribution-map", "Peta Indonesia Persebaran Owner", "choropleth_map", "Melihat owner per provinsi di Indonesia.", "Mengetahui persebaran geografis owner.", "Warna lebih pekat berarti owner lebih banyak.", "Menentukan fokus ekspansi atau penetrasi regional.", "higher_is_better"),
	newDiagram("outlets", "indonesia-distribution-map", "Peta Indonesia Persebaran Outlet", "choropleth_map", "Melihat outlet per provinsi di Indonesia.", "Mengetahui persebaran geografis outlet.", "Warna lebih pekat berarti outlet lebih banyak.", "Menentukan fokus support dan penetrasi regional.", "higher_is_better"),
	newDiagram("leads", "funnel", "Funnel Lead", "funnel", "Melihat perjalanan lead dari stage ke stage.", "Mengetahui titik bocor lead.", "Bandingkan penyusutan antar tahap funnel.", "Menentukan tahap yang paling perlu intervensi.", "higher_is_better"),
	newDiagram("leads", "aging-by-stage", "Aging Lead per Stage", "bar", "Melihat lama lead tertahan per stage.", "Mengetahui stage yang macet.", "Semakin tinggi batang, semakin lama lead tertahan.", "Menentukan SLA atau prioritas follow-up.", "lower_is_better"),
	newDiagram("leads", "assignment-distribution", "Distribusi Assignment Lead", "bar", "Melihat distribusi lead per pemilik saat ini.", "Mengetahui workload lead.", "Bandingkan jumlah lead per current owner.", "Menentukan redistribusi lead bila timpang.", "balanced_is_better"),
	newDiagram("leads", "ownership-transfer-sankey", "Sankey Perpindahan Kepemilikan Lead", "sankey", "Menelusuri perpindahan kepemilikan lead.", "Mengetahui aliran lead antar role.", "Ikuti arah node dan besaran flow.", "Menilai apakah alur distribusi efisien.", "lower_is_better"),
	newDiagram("interactions", "volume-trend", "Tren Volume Interaksi", "line", "Mengukur volume call/chat.", "Mengetahui aktivitas follow-up sales.", "Semakin tinggi garis, semakin banyak interaksi.", "Monitoring produktivitas aktivitas sales.", "higher_is_better"),
	newDiagram("interactions", "remark-distribution", "Distribusi Remark 0-3", "donut", "Melihat hasil call customer.", "Mengetahui kualitas percakapan sales.", "Bandingkan proporsi remark.", "Menilai komposisi invalid, possible, potential, dan closing intent.", "higher_is_better"),
	newDiagram("interactions", "follow-up-compliance", "Kepatuhan Follow-up", "bar", "Melihat follow-up yang dijadwalkan vs dijalankan.", "Mengetahui disiplin follow-up.", "Bandingkan due dan completed.", "Menilai kepatuhan terhadap SLA follow-up.", "higher_is_better"),
	newDiagram("interactions", "first-response-lag", "Jeda Kontak Pertama", "histogram", "Mengukur kecepatan first contact.", "Mengetahui respons awal ke lead baru.", "Lihat sebaran lead berdasarkan lag waktu kontak pertama.", "Menentukan kualitas respons awal tim sales.", "lower_is_better"),
	newDiagram("trainings", "scheduled-vs-completed", "Jadwal vs Selesai Training", "bar", "Membandingkan training terjadwal dan selesai.", "Mengetahui eksekusi training/demo.", "Bandingkan scheduled dan completed per periode.", "Menentukan efektivitas pelaksanaan training.", "higher_is_better"),
	newDiagramWithMetrics("trainings", "training-to-closing-conversion", "Training to Closing Conversion", "bar", "Mengukur efektivitas training terhadap closing.", "Melihat training selesai, closing dari training, dan conversion rate.", "Bandingkan training selesai dengan closing yang lahir setelah training.", "Menentukan apakah demo/training benar-benar mendorong penjualan.", "higher_is_better", []string{"conversion_rate", "completed_training_count", "converted_closing_count"}),
	newDiagramWithMetrics("catalog", "package-popularity", "Popularitas Paket", "bar", "Mengetahui paket paling laku.", "Membandingkan paket berdasarkan jumlah atau omzet snapshot.", "Batang tertinggi menunjukkan paket paling dominan.", "Membantu fokus penawaran paket paling potensial.", "higher_is_better", []string{"confirmed_closing_count", "gross_revenue_snapshot"}),
	newDiagramWithMetrics("catalog", "tenure-popularity", "Popularitas Tenure", "bar", "Mengetahui tenor paling diminati.", "Membandingkan tenor berdasarkan jumlah atau omzet snapshot.", "Batang tertinggi menunjukkan tenor paling disukai.", "Membantu strategi promo berbasis tenor.", "higher_is_better", []string{"confirmed_closing_count", "gross_revenue_snapshot"}),
	newDiagramWithMetrics("catalog", "package-tenure-heatmap", "Heatmap Package x Tenure", "heatmap", "Melihat kombinasi paket dan tenor paling laku.", "Membaca intensitas warna atau nilai setiap sel kombinasi.", "Sel paling kuat menunjukkan bundle unggulan.", "Membantu tim sales memprioritaskan kombinasi penawaran terbaik.", "higher_is_better", []string{"confirmed_closing_count", "gross_revenue_snapshot"}),
	newDiagram("catalog", "promo-adoption-rate", "Promo Adoption Rate", "donut", "Melihat tingkat penggunaan promo.", "Membandingkan no promo, free promo, dan paid promo.", "Proporsi terbesar menunjukkan pola pengambilan promo customer.", "Membantu evaluasi efektivitas promo gratis vs berbayar.", "higher_is_better"),
	newDiagram("catalog", "additional-charge-adoption", "Additional Charge Adoption", "bar", "Melihat seberapa sering promo berbayar dipilih.", "Membandingkan closing dengan biaya tambahan vs tanpa biaya tambahan.", "Batang dengan tambahan charge menunjukkan keberhasilan upsell.", "Membantu mengukur sensitivitas harga terhadap upsell.", "higher_is_better"),
	newDiagram("catalog", "price-history-timeline", "Timeline Riwayat Harga Paket", "line", "Melihat histori perubahan harga plan.", "Membaca titik perubahan harga per tanggal perubahan.", "Lonjakan atau penurunan menunjukkan momen perubahan pricing.", "Membantu audit governance pricing dan dampaknya ke tim sales.", "balanced_is_better"),
	newDiagram("catalog", "promotion-history-timeline", "Timeline Riwayat Promo", "line", "Melihat histori perubahan promo.", "Membaca perubahan promo dan additional charge per tanggal perubahan.", "Terlalu banyak perubahan menunjukkan promo belum stabil.", "Membantu audit perubahan promo dan kontrol katalog.", "balanced_is_better"),
	newDiagramWithMetrics("closings", "closing-trend", "Tren Closing", "line", "Melihat tren closing sales per periode.", "Gunakan metric untuk memilih count, omzet snapshot, atau average ticket size.", "Garis yang naik menandakan hasil closing yang membaik.", "Membantu monitoring ritme closing harian, mingguan, atau bulanan.", "higher_is_better", []string{"closing_count", "confirmed_closing_count", "gross_revenue_snapshot", "average_ticket_size"}),
	newDiagramWithMetrics("closings", "closing-by-sales", "Closing by Sales", "horizontal_bar", "Membandingkan hasil closing antar sales.", "Urutkan sales berdasarkan metric yang dipilih.", "Batang tertinggi menunjukkan sales paling kuat.", "Membantu reward, coaching, dan distribusi beban kerja.", "higher_is_better", []string{"closing_count", "confirmed_closing_count", "gross_revenue_snapshot", "average_ticket_size"}),
	newDiagramWithMetrics("closings", "closing-by-supervisor", "Closing by Supervisor", "horizontal_bar", "Membandingkan hasil closing antar supervisor.", "Urutkan supervisor berdasarkan metric yang dipilih.", "Batang tertinggi menunjukkan tim supervisor paling produktif.", "Membantu evaluasi kepemimpinan tim.", "higher_is_better", []string{"closing_count", "confirmed_closing_count", "gross_revenue_snapshot", "average_ticket_size"}),
	newDiagramWithMetrics("closings", "closing-by-package", "Closing by Package", "bar", "Melihat paket paling laku dari transaksi closing.", "Bandingkan paket berdasarkan jumlah atau omzet snapshot.", "Batang tertinggi menunjukkan paket terlaris di lapangan.", "Membantu prioritas script dan positioning paket.", "higher_is_better", []string{"confirmed_closing_count", "gross_revenue_snapshot"}),
	newDiagramWithMetrics("closings", "closing-by-tenure", "Closing by Tenure", "bar", "Melihat tenor penjualan paling dominan.", "Bandingkan tenor berdasarkan jumlah atau omzet snapshot.", "Batang tertinggi menunjukkan tenor favorit customer.", "Membantu strategi promo dan negosiasi tenor.", "higher_is_better", []string{"confirmed_closing_count", "gross_revenue_snapshot"}),
	newDiagram("closings", "status-distribution", "Distribusi Status Closing", "donut", "Melihat komposisi pending, confirmed, dan rejected.", "Bandingkan proporsi status closing.", "Confirmed idealnya dominan, rejected idealnya kecil.", "Membantu audit proses closing dan reconciliation.", "higher_is_better"),
	newDiagram("closings", "average-ticket-size-trend", "Tren Average Ticket Size", "line", "Melihat nilai rata-rata closing dari waktu ke waktu.", "Baca perubahan rata-rata nominal closing per periode.", "Garis naik menunjukkan nilai deal rata-rata membesar.", "Membantu membedakan pertumbuhan volume vs kualitas nominal.", "higher_is_better"),
	newDiagram("closings", "closing-amount-waterfall", "Waterfall Nilai Closing", "waterfall", "Menjelaskan pembentuk omzet snapshot closing.", "Ikuti alur base price, discount, additional charge, lalu omzet snapshot.", "Terlihat faktor apa yang paling mempengaruhi nilai akhir transaksi.", "Membantu edukasi pricing dan audit diskon.", "higher_is_better"),
	newDiagramWithMetrics("targets", "target-vs-actual", "Target vs Actual Sales", "grouped_bar", "Membandingkan target dan realisasi per sales.", "Lihat gap target dan actual untuk setiap sales.", "Gap negatif menunjukkan target belum tercapai.", "Membantu intervensi supervisor secara cepat.", "higher_is_better", []string{"CONFIRMED_CLOSING_COUNT", "CONFIRMED_CLOSING_AMOUNT", "CALL_CUSTOMER_COUNT", "TRAINING_COUNT"}),
	newDiagramWithMetrics("targets", "target-burnup", "Target Burn-up", "line", "Melihat progres target berjalan sepanjang periode.", "Bandingkan garis aktual kumulatif melawan garis target kumulatif.", "Jarak dua garis menunjukkan aman atau tertinggalnya progres.", "Membantu coaching di tengah periode, bukan di akhir.", "higher_is_better", []string{"CONFIRMED_CLOSING_COUNT", "CONFIRMED_CLOSING_AMOUNT", "CALL_CUSTOMER_COUNT", "TRAINING_COUNT"}),
	newDiagram("kpi", "leaderboard", "KPI Leaderboard", "horizontal_bar", "Merangking sales berdasarkan total skor KPI.", "Urutkan skor tertinggi ke terendah.", "Skor tinggi menunjukkan performa seimbang terhadap KPI aktif.", "Membantu reward, coaching, dan review performa berkala.", "higher_is_better"),
	newDiagram("kpi", "activity-vs-closing-scatter", "Scatter Activity vs Closing", "scatter", "Melihat hubungan aktivitas dan hasil closing.", "Titik di kuadran kanan-atas menunjukkan sales aktif sekaligus efektif.", "Sales yang aktif tapi closing rendah butuh coaching kualitas.", "Membantu evaluasi efisiensi kerja, bukan sekadar kesibukan.", "higher_is_better"),
	newDiagram("wallets", "topup-revenue-trend", "Topup Revenue Trend", "line", "Melihat omset topup per periode.", "Perhatikan naik-turun nominal topup.", "Garis naik menunjukkan cash-in topup membesar.", "Membantu forecast cash dan efektivitas program topup.", "higher_is_better"),
	newDiagram("wallets", "topup-transaction-count", "Topup Transaction Count", "line", "Melihat jumlah transaksi topup per periode.", "Perhatikan frekuensi transaksi topup.", "Membedakan pertumbuhan nominal vs pertumbuhan frekuensi.", "Membantu analisis perilaku pembayaran owner.", "higher_is_better"),
	newDiagram("wallets", "owner-balance-distribution", "Distribusi Saldo Owner", "histogram", "Melihat sebaran saldo owner saat ini.", "Lihat owner menumpuk di bucket saldo mana.", "Banyak saldo nol menunjukkan owner belum siap transaksi.", "Membantu strategi aktivasi topup dan subscribe.", "higher_is_better"),
	newDiagram("wallets", "topup-used-vs-unused", "Topup Used vs Unused", "donut", "Membandingkan dana topup yang sudah terpakai dan masih mengendap.", "Bandingkan proporsi used dan unused.", "Unused terlalu besar berarti banyak saldo belum terkonsumsi.", "Membantu follow-up owner yang sudah topup tapi belum subscribe.", "lower_is_better"),
	newDiagram("wallets", "topup-to-subscribe-lag", "Topup to Subscribe Lag", "histogram", "Melihat jeda topup ke pembelian langganan.", "Lihat bucket hari paling dominan.", "Semakin lama lag, semakin banyak saldo tertahan.", "Membantu desain follow-up pasca topup.", "lower_is_better"),
	newDiagram("wallets", "zero-vs-nonzero-balance", "Zero vs Non-zero Balance", "donut", "Membandingkan owner tanpa saldo vs owner dengan saldo.", "Bandingkan dua proporsi utama kesiapan transaksi.", "Owner bersaldo lebih siap melakukan pembelian.", "Membantu program topup drive dan readiness owner.", "higher_is_better"),
	newDiagram("subscriptions", "active-subscription-trend", "Active Subscription Trend", "line", "Melihat basis subscription aktif per periode.", "Baca total customer aktif pada tiap periode.", "Garis naik menunjukkan basis aktif bertumbuh.", "Membantu monitoring pertumbuhan dan retensi.", "higher_is_better"),
	newDiagram("subscriptions", "activation-vs-expiry-trend", "Activation vs Expiry Trend", "line", "Membandingkan aktivasi subscription baru dengan subscription yang habis.", "Bandingkan dua garis aktivasi dan expiry.", "Activation di atas expiry berarti net growth positif.", "Membantu fokus tim renewal dan akuisisi.", "higher_is_better"),
	newDiagram("subscriptions", "renewal-rate", "Renewal Rate", "line", "Mengukur tingkat perpanjangan subscription.", "Lihat persentase expired yang berhasil diperpanjang.", "Rate tinggi menunjukkan program renewal berjalan baik.", "Membantu evaluasi reminder dan follow-up renewal.", "higher_is_better"),
	newDiagram("subscriptions", "expiry-forecast", "Expiry Forecast 30/60/90", "grouped_bar", "Memprediksi beban jatuh tempo subscription.", "Bandingkan bucket 30, 60, dan 90 hari ke depan.", "Bucket 30 hari tinggi berarti tekanan follow-up dekat.", "Membantu persiapan workload renewal.", "lower_is_better"),
	newDiagram("subscriptions", "package-mix", "Subscription Package Mix", "donut", "Melihat komposisi paket pada subscription aktif.", "Bandingkan proporsi paket aktif saat ini.", "Proporsi membantu membaca segmen basis customer.", "Membantu strategi upsell antar paket.", "higher_is_better"),
	newDiagram("subscriptions", "tenure-mix", "Subscription Tenure Mix", "donut", "Melihat komposisi tenor pada subscription aktif.", "Bandingkan proporsi duration aktif saat ini.", "Tenor panjang menunjukkan retensi dan komitmen lebih baik.", "Membantu strategi promo tenor.", "higher_is_better"),
	newDiagram("subscriptions", "days-remaining-histogram", "Days Remaining Histogram", "histogram", "Melihat sebaran sisa hari subscription aktif.", "Lihat penumpukan akun di bucket kritis atau aman.", "Banyak akun di bucket rendah berarti beban renewal tinggi.", "Membantu scheduling reminder renewal.", "lower_is_better"),
	newDiagram("subscriptions", "churn-bucket-trend", "Churn Bucket Trend", "stacked_bar", "Melihat outlet EXPIRED vs NOT_SUBSCRIBE per periode.", "Bandingkan churn pendek dan churn berat.", "NOT_SUBSCRIBE tinggi berarti win-back makin sulit.", "Membantu strategi retention dan reaktivasi.", "lower_is_better"),
	newDiagram("reconciliation", "success-rate", "Reconciliation Success Rate", "line", "Mengukur persentase reconciliation yang berhasil confirmed.", "Lihat confirmed dibanding total proses reconciliation.", "Rate tinggi menunjukkan matching engine dan data lebih sehat.", "Membantu evaluasi kualitas rule dan data transaksi.", "higher_is_better"),
	newDiagram("reconciliation", "issue-by-type", "Issue by Type", "bar", "Melihat tipe issue reconciliation yang paling dominan.", "Urutkan issue_type dari terbanyak ke tersedikit.", "Issue dominan menjadi prioritas perbaikan data atau proses.", "Membantu backlog fixing operasional.", "lower_is_better"),
	newDiagram("reconciliation", "issue-aging", "Issue Aging", "bar", "Melihat usia issue reconciliation yang tertahan.", "Lihat bucket umur issue terbanyak.", "Issue tua menunjukkan backlog administrasi atau mismatch sulit.", "Membantu penetapan SLA penyelesaian issue.", "lower_is_better"),
	newDiagram("reconciliation", "auto-vs-manual", "Auto vs Manual Reconciliation", "donut", "Membandingkan reconciliation otomatis dan manual.", "Bandingkan proporsi auto dan manual.", "Auto lebih tinggi berarti engine semakin efisien.", "Membantu evaluasi otomatisasi rule matching.", "higher_is_better"),
	newDiagram("reconciliation", "hanging-transaction-trend", "Hanging Transaction Trend", "line", "Melihat tren issue transaksi menggantung.", "Perhatikan naik-turun issue OPEN per periode.", "Issue OPEN yang naik berarti risiko laporan makin besar.", "Membantu monitoring harian tim admin.", "lower_is_better"),
	newDiagram("reconciliation", "revenue-vs-closing-period-compare", "Revenue vs Closing Period Compare", "grouped_bar", "Memisahkan omset topup dan performa closing.", "Bandingkan topup revenue dengan closing revenue snapshot di periode yang sama.", "Perbedaan bukan selalu masalah, tapi perlu bisa dijelaskan.", "Membantu edukasi laporan manajemen agar tidak double counting.", "balanced_is_better"),
	newDiagram("partners", "partner-growth-trend", "Partner Growth Trend", "line", "Melihat pertumbuhan partner baru.", "Perhatikan jumlah partner baru per periode.", "Garis naik menunjukkan program akuisisi partner berkembang.", "Membantu evaluasi pertumbuhan channel partner.", "higher_is_better"),
	newDiagram("partners", "partner-type-distribution", "Partner Type Distribution", "donut", "Melihat komposisi jenis partner.", "Bandingkan proporsi setiap tipe partner.", "Tipe dominan menunjukkan struktur channel saat ini.", "Membantu fokus akuisisi pada tipe partner terbaik.", "higher_is_better"),
	newDiagram("partners", "referral-count-per-partner", "Referral Count per Partner", "horizontal_bar", "Mengukur kontribusi referral tiap partner.", "Urutkan partner berdasarkan jumlah referral.", "Partner produktif terlihat dari referral terbanyak.", "Membantu prioritas relationship dan insentif.", "higher_is_better"),
	newDiagram("partners", "referral-conversion-per-partner", "Referral Conversion per Partner", "horizontal_bar", "Mengukur kualitas referral tiap partner.", "Bandingkan referral dengan closing hasil referral.", "Conversion rate tinggi menunjukkan referral berkualitas.", "Membantu evaluasi partner yang perlu dibina atau ditingkatkan.", "higher_is_better"),
	newDiagram("partners", "partner-pic-workload", "Partner PIC Workload", "stacked_bar", "Melihat beban partner per PIC Sales.", "Bandingkan jumlah partner aktif/nonaktif yang ditangani tiap PIC.", "PIC yang terlalu penuh terlihat menonjol.", "Membantu redistribusi partner agar beban lebih sehat.", "balanced_is_better"),
	newDiagram("partners", "call-mitra-frequency", "Call Mitra Frequency", "line", "Mengukur intensitas call ke mitra.", "Lihat jumlah call partner per periode.", "Garis turun bisa berarti hubungan partner kurang terjaga.", "Membantu penjadwalan silaturahmi partner.", "higher_is_better"),
	newDiagram("partners", "partner-inactivity-aging", "Partner Inactivity Aging", "bar", "Mengetahui partner yang dorman.", "Lihat bucket hari tanpa aktivitas partner.", "Bucket tua menunjukkan partner pasif lebih lama.", "Membantu program re-engagement partner.", "lower_is_better"),
	newDiagram("partners", "partner-region-distribution", "Partner Region Distribution", "bar", "Melihat persebaran partner berdasarkan wilayah referral.", "Bandingkan jumlah partner per wilayah.", "Wilayah kosong atau lemah terlihat jelas.", "Membantu ekspansi partner di area kurang ter-cover.", "higher_is_better"),
	newDiagram("commissions", "commission-earned-trend", "Commission Earned Trend", "line", "Melihat accrual komisi per periode.", "Perhatikan nominal komisi yang terbentuk.", "Garis naik berarti beban komisi bertambah bersama aktivitas partner.", "Membantu forecast kewajiban komisi.", "balanced_is_better"),
	newDiagram("commissions", "paid-vs-unpaid", "Paid vs Unpaid Commission", "donut", "Membandingkan komisi yang sudah dibayar dan belum dibayar.", "Bandingkan proporsi paid dan unpaid.", "Unpaid besar berarti kewajiban payout menumpuk.", "Membantu prioritas proses payout.", "lower_is_better"),
	newDiagram("commissions", "commission-aging", "Commission Aging", "bar", "Melihat umur komisi yang belum dibayar.", "Lihat bucket usia earning yang masih unpaid.", "Banyak komisi tua berarti proses payout lambat.", "Membantu evaluasi SLA pembayaran komisi.", "lower_is_better"),
	newDiagram("commissions", "commission-by-partner-type", "Commission by Partner Type", "bar", "Mengetahui tipe partner penyumbang beban komisi.", "Bandingkan nominal komisi per tipe partner.", "Tipe mahal/murah terlihat dari total nominal.", "Membantu evaluasi efisiensi rule komisi.", "balanced_is_better"),
	newDiagram("commissions", "commission-by-package", "Commission by Package", "bar", "Mengetahui paket yang paling memicu komisi.", "Bandingkan nominal komisi per paket closing.", "Paket tertentu bisa terlihat lebih berat di sisi komisi.", "Membantu review profitabilitas paket.", "balanced_is_better"),
	newDiagram("commissions", "payout-waterfall", "Payout Waterfall", "waterfall", "Melihat alur nominal dari earned ke approved lalu paid.", "Bandingkan besaran di setiap tahap payout.", "Gap besar menunjukkan titik delay approval/pembayaran.", "Membantu mempercepat flow payout.", "higher_is_better"),
	newDiagram("commissions", "rule-history-timeline", "Commission Rule History Timeline", "line", "Melihat histori perubahan nilai komisi master.", "Baca perubahan mode/nilai komisi partner type dari audit log.", "Perubahan terlalu sering bisa menunjukkan governance belum stabil.", "Membantu audit perubahan rule komisi.", "balanced_is_better"),
	newDiagram("commissions", "snapshot-vs-current", "Snapshot vs Current Commission", "grouped_bar", "Membandingkan komisi snapshot historis dengan rule saat ini.", "Bandingkan nominal snapshot dan simulasi current rule.", "Delta idealnya kecil atau nol pada histori yang benar-benar statis.", "Membantu validasi historical integrity.", "balanced_is_better"),
	newDiagram("audit", "log-volume-by-module", "Audit Log Volume by Module", "bar", "Melihat modul yang paling sering berubah.", "Bandingkan jumlah audit log per modul.", "Modul dengan volume tinggi butuh pengawasan lebih dekat.", "Membantu fokus governance data.", "balanced_is_better"),
	newDiagram("audit", "actor-activity-chart", "Actor Activity Chart", "horizontal_bar", "Melihat user yang paling aktif mengubah data.", "Bandingkan volume audit per actor.", "Outlier bisa menjadi sinyal aktivitas abnormal atau workload tinggi.", "Membantu audit aktivitas user.", "balanced_is_better"),
	newDiagram("audit", "restore-vs-delete-trend", "Restore vs Delete Trend", "line", "Membandingkan operasi restore dan delete dari waktu ke waktu.", "Lihat tren delete vs restore per periode.", "Restore tinggi bisa menandakan salah hapus atau UX kurang jelas.", "Membantu evaluasi kualitas operasi data.", "lower_is_better"),
	newDiagram("audit", "backend-error-code-frequency", "Backend Error Code Frequency", "bar", "Melihat frekuensi failure backend yang persisted.", "Bandingkan jumlah failure yang tercatat di storage backend.", "Error dominan menjadi prioritas perbaikan operasional.", "Membantu backlog fixing teknis.", "lower_is_better"),
	newDiagram("imports", "batches-per-profile", "Import Batches per Profile", "bar", "Melihat profil import yang paling sering dipakai.", "Bandingkan jumlah batch per profile import.", "Profile yang dominan menunjukkan beban operasional terbesar.", "Membantu fokus perbaikan template import.", "balanced_is_better"),
	newDiagram("imports", "success-vs-failed", "Import Success vs Failed", "donut", "Melihat komposisi import sukses dan gagal.", "Bandingkan SUCCESS dan FAILED pada batch import.", "Fail rate tinggi berarti operasional import belum stabil.", "Membantu prioritas stabilisasi modul import.", "higher_is_better"),
	newDiagram("imports", "invalid-rows-distribution", "Invalid Rows Distribution", "histogram", "Melihat distribusi banyaknya row invalid per batch.", "Lihat batch terkumpul di bucket invalid row mana.", "Semakin banyak batch di bucket tinggi, kualitas file makin buruk.", "Membantu edukasi uploader dan quality control file.", "lower_is_better"),
	newDiagram("imports", "validation-error-by-profile", "Validation Error by Profile", "grouped_bar", "Melihat profile yang paling banyak menghasilkan invalid rows atau validation failed.", "Bandingkan invalid row count dan failed batch count per profile.", "Profile bermasalah akan terlihat dominan pada kedua indikator ini.", "Membantu menentukan template/profile prioritas perbaikan.", "lower_is_better"),
	newDiagram("imports", "duplicate-detection-rate", "Duplicate Detection Rate", "line", "Melihat indikasi duplicate data dalam import.", "Perhatikan duplicate rate per periode.", "Rate tinggi menunjukkan sumber data makin noisy atau governance input lemah.", "Membantu backlog dedupe dan quality gate import.", "lower_is_better"),
	newDiagram("imports", "import-duration-trend", "Import Duration Trend", "line", "Melihat durasi rata-rata proses import.", "Perhatikan tren menit proses import dari waktu ke waktu.", "Durasi naik menandakan worker atau file semakin berat.", "Membantu monitoring performa background job import.", "lower_is_better"),
	newDiagram("imports", "batch-status-funnel", "Batch Status Funnel", "funnel", "Melihat seberapa banyak batch lolos dari upload sampai commit.", "Ikuti penyusutan UPLOADED ke VALIDATED ke COMMITTED.", "Penyusutan besar di tengah funnel menunjukkan titik kegagalan utama.", "Membantu fokus perbaikan per tahap pipeline import.", "higher_is_better"),
	newDiagram("imports", "uploader-activity", "Import Uploader Activity", "horizontal_bar", "Melihat admin yang paling aktif upload file.", "Urutkan uploader berdasarkan jumlah batch.", "Distribusi yang timpang bisa berarti beban kerja tidak merata.", "Membantu evaluasi operasional import admin.", "balanced_is_better"),
	newDiagram("imports", "file-history-usage", "File History Usage", "line", "Placeholder analytics untuk viewer/download histori file import.", "Saat ini baca catatan source availability pada response.", "Belum ada event usage yang dipersist, jadi chart masih kontrak kosong.", "Membantu roadmap observability histori file.", "balanced_is_better"),
	newDiagram("executive", "end-to-end-funnel", "End-to-End Business Funnel", "funnel", "Melihat alur owner sampai subscription aktif.", "Bandingkan jumlah entity yang lolos di setiap tahap funnel bisnis.", "Penyusutan terbesar menunjukkan titik bocor utama lintas modul.", "Membantu keputusan manajemen lintas tim.", "higher_is_better"),
	newDiagram("executive", "revenue-closing-active-subscription-board", "Revenue vs Closing vs Active Subscription", "grouped_bar", "Memisahkan topup revenue, closing revenue snapshot, dan active subscription.", "Bandingkan tiga metrik inti bisnis secara terpisah.", "Perbedaan antar metrik membantu mencegah salah tafsir omzet vs performa sales vs basis pelanggan aktif.", "Membantu board level review yang tidak double counting.", "balanced_is_better"),
	newDiagramWithMetrics("executive", "monthly-operating-review-board", "Monthly Operating Review Board", "mixed", "Ringkasan KPI operasional bulanan.", "Baca metric inti per bulan beserta delta terhadap baseline bila diaktifkan.", "Metrik yang tertinggal langsung terlihat dalam satu board.", "Membantu bahan rapat manajemen bulanan.", "higher_is_better", []string{"owner_count", "outlet_count", "lead_count", "confirmed_closing_count", "topup_revenue", "active_subscription_count"}),
	newDiagramWithMetrics("executive", "north-star-kpi-trend", "North Star KPI Trend", "line", "Melihat tren KPI inti jangka menengah.", "Bandingkan beberapa garis KPI utama dalam periode yang sama.", "Arah kolektif KPI inti membantu membaca kesehatan bisnis secara menyeluruh.", "Membantu monitoring north star metric perusahaan.", "higher_is_better", []string{"owner_count", "confirmed_closing_count", "topup_revenue", "active_subscription_count"}),
	newDiagram("executive", "data-quality-score-by-module", "Data Quality Score by Module", "bar", "Mengukur kualitas data operasional per modul backend.", "Bandingkan score 0-100 antar modul.", "Modul dengan score rendah perlu prioritas cleansing atau hardening proses.", "Membantu prioritas perbaikan kualitas data.", "higher_is_better"),
	newDiagramWithMetrics("custom", "multi-series-trend", "Custom Multi-series Trend", "line", "Membandingkan banyak metrik dalam satu grafik waktu.", "Setiap garis mewakili satu metric yang dipilih user.", "Gerak naik-turun bersama membantu membaca korelasi kasar antar metrik.", "Membantu analyst membuat analisis ad-hoc lintas domain.", "balanced_is_better", []string{"owner_count", "outlet_count", "lead_count", "confirmed_closing_count", "topup_revenue", "active_subscription_count"}),
	newDiagramWithMetrics("custom", "metric-comparison-board", "Custom Metric Comparison Board", "grouped_bar", "Membandingkan banyak metric pada satu periode.", "Bandingkan nilai current dan delta metric yang dipilih.", "Gap antar metric membantu melihat area paling unggul atau tertinggal.", "Membantu review performa cepat sesuai kebutuhan analyst.", "balanced_is_better", []string{"owner_count", "outlet_count", "lead_count", "confirmed_closing_count", "topup_revenue", "active_subscription_count"}),
	newDiagramWithMetrics("custom", "region-comparison-board", "Custom Region Comparison Board", "grouped_bar", "Membandingkan metrik antar provinsi atau kota.", "X-axis menampilkan region compare_series yang dipilih, sedangkan seri menampilkan metric.", "Region yang paling kuat dan lemah terlihat jelas.", "Membantu prioritas ekspansi dan perhatian regional.", "higher_is_better", []string{"owner_count", "outlet_count", "lead_count", "confirmed_closing_count", "topup_revenue"}),
	newDiagram("subscriptions", "cohort-retention", "Subscription Cohort Retention", "heatmap", "Melihat ketahanan cohort pelanggan berlangganan.", "Baca cohort berdasarkan bulan aktivasi dan retention rate per offset bulan.", "Cohort yang cepat dingin menunjukkan masalah onboarding atau retention awal.", "Membantu strategi onboarding dan renewal.", "higher_is_better"),
	newDiagram("executive", "forecast-summary-board", "Forecast Summary Board", "mixed", "Merangkum risiko operasional ke depan.", "Baca bucket expiry, open issue, unpaid commission, dan failed import dalam satu board.", "Risk score tinggi menunjukkan backlog atau risiko bulan berikutnya meningkat.", "Membantu persiapan operasional dan mitigasi dini.", "lower_is_better"),
	newDiagramWithMetrics("custom", "comparison-impact-summary", "Comparison Impact Summary", "bar", "Merangkum dampak comparison banyak metric sekaligus.", "Lihat delta dan delta percent per metric terhadap baseline.", "Metric dengan delta negatif terbesar menjadi prioritas perbaikan cepat.", "Membantu analyst menyusun summary perubahan periodik.", "balanced_is_better", []string{"owner_count", "confirmed_closing_count", "topup_revenue", "active_subscription_count"}),
}

func newDiagram(module, key, name, chartType, function, purpose, howToRead, goal, polarity string) DiagramCatalogItem {
	queryPath := fmt.Sprintf("/api/v1/analytics/%s/%s/query", module, key)
	return DiagramCatalogItem{
		Module:            module,
		Key:               key,
		Name:              name,
		Type:              chartType,
		Function:          function,
		Purpose:           purpose,
		HowToRead:         howToRead,
		AnalysisGoal:      goal,
		SupportedMetrics:  []string{},
		SupportedFilters:  []string{"province", "city", "sales_id", "supervisor_id", "owner_id", "outlet_id", "status"},
		SupportedCompare:  []string{"previous_period", "previous_month", "previous_year", "custom_period"},
		QueryEndpoint:     queryPath,
		PolarityRule:      polarity,
		ExportAvailable:   false,
		ComparisonEnabled: true,
	}
}

func newDiagramWithMetrics(module, key, name, chartType, function, purpose, howToRead, goal, polarity string, metrics []string) DiagramCatalogItem {
	item := newDiagram(module, key, name, chartType, function, purpose, howToRead, goal, polarity)
	item.SupportedMetrics = append([]string{}, metrics...)
	return item
}

func Catalog() []DiagramCatalogItem {
	items := make([]DiagramCatalogItem, len(registry))
	copy(items, registry)
	return items
}

func CatalogByModule(module string) []DiagramCatalogItem {
	items := make([]DiagramCatalogItem, 0)
	for _, item := range registry {
		if item.Module == module {
			items = append(items, item)
		}
	}
	return items
}

func FindDiagram(module, key string) (DiagramCatalogItem, bool) {
	for _, item := range registry {
		if item.Module == module && item.Key == key {
			return item, true
		}
	}
	return DiagramCatalogItem{}, false
}
